### ISSUE TITLE
Visibility of  "Description" and "IsHealthy" of HealthCheckResponsePayload object 

### ISSUE THREAD

**Issue by SergeiIkkert** [bugfi5h/Alexa-Smart-Home#1]
I would like to check whether my Lamda adapter responds correctly to the "HealthCheckRequests". In my tests I would like to access the property "IsHealthy" of the class HealthCheckResponsePayload. This is private!
I think this property must be "public". At least the getters!
The same applies to the property "Description".
 I would like to know your opinion?
Thanks for the cool API!

**Comment by bugfi5h** [comment]
Hello,
glad to hear you like the API.
You are right! I changed the properties so they have a public getter.
It was the way I intented it to be, but I have to forgot to change it proberly.

**Comment by SergeiIkkert** [comment]
Super response time! Supper work! I will continue to use the API and look for improvements. :)
