### ISSUE TITLE
ERROR: ReadJson

### ISSUE THREAD

**Issue by FrankDoersam** [bugfi5h/Alexa-Smart-Home#3]
Hello,

Thanks for the big library. We are using version 2 of Alexa Smart Home. after we switched to version 3 and rewrote the methods in the skill to version 3, we get a ReadJson error in CloudWatch. If the error is known, there is a solution here.
Thanks in advance.
Best regards
Frank Dörsam

**Comment by bugfi5h** [comment]
Hello Mr Dörsam,

where exactly does the error occur? What was the incoming request?
I will try to find the error asap
