### ISSUE TITLE
Two issues with payload v3

### ISSUE THREAD

**Issue by raphpa** [bugfi5h/Alexa-Smart-Home#4]
Thanks for your library. I used it in a smart home skill and it saved me quite some work for sure.

Just two things I noticed and fixed for myself already:

1. AcceptGrant Directive/Response/Error is missing
[https://developer.amazon.com/de/docs/device-apis/alexa-authorization.html](https://developer.amazon.com/de/docs/device-apis/alexa-authorization.html)

2. ProactivelyReported and Retrieveable should not be part of Capability, but of Properties
[https://developer.amazon.com/de/docs/device-apis/alexa-discovery.html](https://developer.amazon.com/de/docs/device-apis/alexa-discovery.html)

Best regards

**Comment by bugfi5h** [comment]
Thanks for your feedback, I will fix it asap. The thing with missing things
is that amazon is working a lot on payload 3. There are certaintly a few
new things i am not supporting yet. If you find something missing, feel
free to send a pull request if you implemeted it already.

Best regards.

Am 30.12.2017 17:15 schrieb "raphpa" <notifications@github.com>:

**Comment by bugfi5h** [comment]
So I integrated the acceptgrant and fixed the second one. Thanks again for the feedback
