### ISSUE TITLE
Migration to Payloadversion 3

### ISSUE THREAD

**Issue by SergeiIkkert** [bugfi5h/Alexa-Smart-Home#5]
Hi I already use your library and would like to change my code to Paiload V3. On the project side, the signature of the FunctionHandler has confuse me. Is that really true!

  public SmartHome**Request** FunctionHandler (string jsonString)

Must be the return value of the handler, not the SmartHomeResponse, or! Maybe I got it wrong! Can you give me an example of the Function Handler? Like in V2.

Thank you for your help.

**Comment by bugfi5h** [comment]
Hi, thanks for using my libary.
Here is a FunctionHandler similar to the V2 example:
```csharp
public SmartHomeResponse FunctionHandler(SmartHomeRequest input, ILambdaContext context)
        {
            SmartHomeResponse shResponse = null;
            var logger = context.Logger;
            switch (input.Event.Header.Namespace)
            {
                case Namespaces.ALEXA_DISCOVERY:
                    logger.LogLine("DiscoverRequest");
                    shResponse = handleDiscovery(input, context);
                    break;
                case Namespaces.CONTROL:
                    logger.LogLine("ControlRequest");
                    shResponse = handleRequest(input, context);
                    break;
                default:
                    logger.LogLine("UnknownNamespaceRequest. Namespace= " + input.Header.Namespace);
                    shResponse = handleUnknownNamespaceError(input, context);
                    break;
            }
            return shResponse;
        }
```

For examples to fill a response you can look through the testcases. Hope this helps.
Best Regards,

**Comment by raphpa** [comment]
Does that actually work? I never got LambdaSerializer to convert enums as string instead of int.
So I used 

`string responseString = JsonConvert.SerializeObject(response, new StringEnumConverter());`

and returned that as string. (Actually returning a stream now as it seems to be faster ;) )

**Comment by SergeiIkkert** [comment]
Hi, I use the library as a Nuget package. After the update to version 1.1.1-beta, I expected it to contain the Payload V3 functionality. As described on the project page. (For example, SmartHomeRequest request.Directive property must be present.) Did I understand something flimsy or is the Nuget out of date? The Master brunch looks completely different than my Nuget Packet.

<img width="695" alt="rkon alexa net" src="https://user-images.githubusercontent.com/22621678/35484800-84bd8f90-0455-11e8-89fd-d98037539c24.PNG">

<img width="311" alt="rkon alexa net_masterpng" src="https://user-images.githubusercontent.com/22621678/35484801-8966089c-0455-11e8-8589-30980c21db2d.PNG">

**Comment by bugfi5h** [comment]
Sorry that I did not answer in time. My time at the moment is very limited. There went something wrong with the nuget package and I didn't double check it. I uploaded a new Version, which should include Payload 3. Sorry for the inconvenience.
Best regards,
