### ISSUE TITLE
official capabilities of Alexa 

### ISSUE THREAD

**Issue by FrankDoersam** [bugfi5h/Alexa-Smart-Home#6]
Good evening,

Is it possible to include the official capabilities of Alexa (Alexa.ColorTemperatureController, Alexa.PowerController) in the library?

Thanks in advance!

Kind regards
Frank

**Comment by raphpa** [comment]
They are of type AlexaInterface. Like

```
AlexaInterface capability = new AlexaInterface(Namespaces.ALEXA_POWERCONTROLLER, "3", propertyNames, false, false);
endpoint.Capability.Add(capability);
```

**Comment by SergeiIkkert** [comment]
Hi, I use the library as a Nuget package. After the update to version 1.1.1-beta, I expected it to contain the Payload V3 functionality. As described on the project page. (For example, SmartHomeRequest **request.Directive** property must be present.) Did I understand something flimsy or is the Nuget out of date? The Master brunch looks completely different than my Nuget Packet.
